POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRvcnJyIiwiaWQiOiI2NzgxMDliZWIyZTNhNWYxOGU3MTQ3YjQiLCJpYXQiOjE3MzY1MDk5OTF9._-qV_6HsJ4j-ACKmgy0FNbAmjUzsK1_2Xmre3yYM18M

{
    "title": "Uusi blogi",
    "author": "Kikkare",
    "url": "http://example.com",
    "likes": 9,
    "userId": "677d1c269c7e2779e1def1a2"
}